from app.domain.base.domain_exception import DomainException


class UserException(DomainException):
    ...
